'use client';
import { useMemo, useState } from 'react';
import { SERVICE_LABEL } from '@/lib/wash';

export default function Home() {
  const [vehicle,setVehicle]=useState('auto');
  const [service,setService]=useState('full');
  const [form,setForm]=useState({phone:'',firstName:'',lastName:'',dni:''});
  const [result,setResult]=useState<any>(null);
  const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const services=useMemo(()=> vehicle==='moto' ? ['moto_completo'] : ['full','habitaculo','exterior','premium'],[vehicle]);
  function changeVehicle(v:string){setVehicle(v);setService(v==='moto'?'moto_completo':'full')}
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setResult(null);try{const r=await fetch('/api/washes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,vehicle,service})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo registrar');setResult(d)}catch(err:any){setError(err.message)}finally{setLoading(false)}}
  if(result) return <main className="wrap"><div className="top"><div><div className="brand">LAVA<span>DERO</span></div><div className="sub">Seguimiento de vehículo por QR</div></div></div><div className="card qrbox"><div className="success big">¡Vehículo registrado!</div><p>Escaneá este QR con el celular para ver el estado del lavado en tiempo real.</p><img src={result.qr} alt="QR de seguimiento"/><strong>{result.vehicleLabel} · {result.serviceLabel}</strong><a className="btn secondary" href={result.trackingUrl} target="_blank">Abrir seguimiento</a><button className="btn" onClick={()=>setResult(null)}>Registrar otro vehículo</button></div><div className="footer">El QR es único para este lavado.</div></main>;
  return <main className="wrap"><div className="top"><div><div className="brand">LAVA<span>DERO</span></div><div className="sub">Registro y seguimiento de vehículos</div></div><a className="btn secondary" href="/admin">Personal</a></div><form className="card grid" onSubmit={submit}><h1 className="section-title">Datos del cliente</h1><div className="grid grid2"><div><label className="label">Teléfono</label><input className="input" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">DNI</label><input className="input" required value={form.dni} onChange={e=>setForm({...form,dni:e.target.value})}/></div><div><label className="label">Nombre</label><input className="input" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></div><div><label className="label">Apellido</label><input className="input" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></div></div><h2 className="section-title">Vehículo</h2><div className="grid grid3">{[['auto','Auto'],['camioneta','Camioneta'],['moto','Moto']].map(([v,l])=><label className="choice" key={v}><input type="radio" checked={vehicle===v} onChange={()=>changeVehicle(v)}/><strong>{l}</strong></label>)}</div><h2 className="section-title">Servicio</h2><div className="grid grid2">{services.map(s=><label className="choice" key={s}><input type="radio" checked={service===s} onChange={()=>setService(s)}/><strong>{SERVICE_LABEL[s as keyof typeof SERVICE_LABEL]}</strong><small>{s==='full'?'Lavado total del vehículo':s==='habitaculo'?'Solo interior':s==='exterior'?'Solo exterior':s==='premium'?'Lavado completo + cera':'Lavado completo de moto'}</small></label>)}</div>{error&&<div className="error">{error}</div>}<button className="btn" disabled={loading}>{loading?'Registrando...':'Registrar lavado y generar QR'}</button></form><div className="footer">Sistema de lavadero · Vercel + PostgreSQL</div></main>
}
